baseURL = "https://m-fujimoto.github.io/"
languageCode = "en-GB"
title = "Fab"
theme = "Fab"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3

  [[menu.main]]
    name = "Categories"
    pre = "category"
    url = "/categories/"
    weight = 4

  [[menu.main]]
    name = "Tags"
    pre = "tag"
    url = "/tags/"
    weight = 5

[taxonomies]
  tag = "tags"
  category = "categories"

[params]
  mydateformat = "2 Jan 2006"
  authorName = "masayoshi"

[permalinks]
  posts = '/:year/:month/:title/'
